version: '3'
services:
  jdx-postgres:
    restart: always
    image: 'postgres:10.4-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jdx_reference_backend_application
    ports:
      - '5433:5432'
    volumes:
      - './datastore/postgres:/var/lib/postgresql/data'